### ISSUE TITLE
swank:init-project fails if project_config (.ensime) starts with a ;

### ISSUE THREAD

**Issue by teigen** [mads-hartmann/ensime.tmbundle#1]
Handling RPC: (swank:connection-info)
Writing: 000076(:return (:ok (:pid nil :server-implementation (:name "ENSIMEserver") :machine nil :features nil :version "0.0.1")) 0)
`)' expected but` ' found
Writing: 000019(:reader-error 203 "nil")
Error in socket reader: java.io.EOFException: End of file reached in socket reader

**Comment by mads-hartmann** [comment]
Hey Jon-anders

Can you paste the entire .ensime file? I tried with the following 

<pre><code>;
(:project-package "com.sidewayscoding" 
 :use-sbt t 
 :root-dir "/Users/Mads/dev/projects/functional_dictionary/")</code></pre> 


And ti works

**Comment by mads-hartmann** [comment]
My bad - it does indeed crash. I'll investigate :)

**Comment by mads-hartmann** [comment]
A fix is in master now. 

Mads
