### ISSUE TITLE
Cannot Start the backend

### ISSUE THREAD

**Issue by channingwalton** [mads-hartmann/ensime.tmbundle#2]
Hi,
I followed the instructions to get it running but when I run ⌃⇧R and chooise 'Start Ensime' the following gets pasted into my open file window: 

/bin/bash: Start: command not found

**Comment by mads-hartmann** [comment]
Somehow the shell command is wrong. I've added something in the newest version of the bundle that will print what the command it tried to use looked like to make it easier to debug :) 

Please get the newest version of the bundle and paste the shell command that it's using to start the server here so I can try to help you :)

**Comment by channingwalton** [comment]
just caught up and it output exactly the same thing

**Comment by mads-hartmann** [comment]
Is that the only output? It doesn't print the command it used at the top? Are you using cutting-edge version of TextMate?

**Comment by channingwalton** [comment]
I'm using textmate 1.5.10, just grabbed the latest ensime. When I type ⌃⇧R  it offers Input and Output options, is there any particular combination I should use?

**Comment by channingwalton** [comment]
Got it working. I removed all my textmate bundles and started again - not sure what the cause was but there it is.

Sorry for the stress :)

**Comment by mads-hartmann** [comment]
Awesome, you just got me worried there ;) Hope you enjoy it.
