### ISSUE TITLE
On case-sensitive file systems, scalaparser.rb is not found

### ISSUE THREAD

**Issue by d6y** [mads-hartmann/ensime.tmbundle#3]
On a case-sensitive file system, if you start TextMate and then try to start ENSIME server you see:

/Users/richard/Library/Application Support/TextMate/Pristine Copy/Bundles/ENSIME.tmbundle/Support/ensime.rb:15:in `require': no such file to load -- /Users/richard/Library/Application Support/TextMate/Pristine Copy/Bundles/ENSIME.tmbundle/Support/scalaparser.rb (LoadError) from /Users/richard/Library/Application Support/TextMate/Pristine Copy/Bundles/ENSIME.tmbundle/Support/ensime.rb:15 from /tmp/temp_textmate.Kb9EHX:8:in`require' from /tmp/temp_textmate.Kb9EHX:8

The work around is to edit line 15 of /Users/$YOU/Library/Application Support/TextMate/Pristine Copy/Bundles/ENSIME.tmbundle/Support/ensime.rb and change:

require BUNDLE_LIB + "scalaparser.rb"

...to...

require BUNDLE_LIB + "ScalaParser.rb"

(Or I guess rename the scalaparser file)

**Comment by mads-hartmann** [comment]
Thanks Richard, the change is in master :)
