### ISSUE TITLE
Cannot Initialize Ensime Properly

### ISSUE THREAD

**Issue by basetta** [mads-hartmann/ensime.tmbundle#9]
Hi,
I am trying to use ensime but i got this error after the inizialize command:

Writing: 000052(:return (:abort 202 "Malformed swank:init-project call: (swank:init-project)") 0)

I tried to remove all the bundles keeping only scala and esime.

You know how to fix this problem ?

Thx

**Comment by mads-hartmann** [comment]
Hi, 

It seems to me that the error message indicates that your .ensime file is malformed. Can you post the contents of your .ensime file here please?

**Comment by basetta** [comment]
Recreated the .ensime file solved the problem. Thx a lot :)

**Comment by mads-hartmann** [comment]
No problem - This is still very much work in progress so let me know if you find any other errors :) 

Mads
